# Generated by Django 5.0.1 on 2024-02-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('referred_doctor', models.CharField(max_length=100)),
                ('test_type', models.CharField(max_length=100)),
                ('test_notes', models.TextField()),
            ],
        ),
    ]
