# Generated by Django 5.0.1 on 2024-02-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConductMedicalTest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='id',
        ),
        migrations.RemoveField(
            model_name='testrecord',
            name='test_type',
        ),
        migrations.AddField(
            model_name='testrecord',
            name='test_record_number',
            field=models.AutoField(default=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrecord',
            name='test_types',
            field=models.CharField(choices=[('Blood Test ($50)', 'Blood Test ($50)'), ('Urinalysis ($40)', 'Urinalysis ($40)'), ('X-Ray ($100)', 'X-Ray ($100)'), ('MRI ($200)', 'MRI ($200)'), ('CT Scan ($150)', 'CT Scan ($150)'), ('Ultrasound ($80)', 'Ultrasound ($80)'), ('ECG ($60)', 'ECG ($60)'), ('Endoscopy ($180)', 'Endoscopy ($180)'), ('Colonoscopy ($200)', 'Colonoscopy ($200)'), ('Biopsy ($120)', 'Biopsy ($120)')], default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='patient_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='referred_doctor',
            field=models.CharField(max_length=255),
        ),
    ]
