# Generated by Django 5.0.2 on 2024-02-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("cabin_no", models.CharField(max_length=10)),
                ("total_bill", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_paid", models.BooleanField(default=False)),
            ],
        ),
    ]
