# Generated by Django 5.0.2 on 2024-02-21 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App_DischargePatient", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="id",
            new_name="patientId",
        ),
    ]
