# Generated by Django 5.0.2 on 2024-02-22 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App_DischargePatient", "0002_rename_id_patient_patientid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="cabin_no",
            new_name="cabinNo",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="payment_paid",
            new_name="paymentPaid",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="total_bill",
            new_name="totalBill",
        ),
    ]
