# Generated by Django 5.0.2 on 2024-02-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App_Payment", "0002_paymentmodel_delete_app_makepayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(max_length=20)),
                ("patient_name", models.CharField(max_length=100)),
                ("cabin_number", models.IntegerField()),
                (
                    "reports_bill",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "medicine_bill",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cabin_bill",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_bill",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
    ]
