# Generated by Django 5.0.2 on 2024-02-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App_Payment", "0003_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="cabin_number",
            field=models.CharField(max_length=100),
        ),
    ]
