# Generated by Django 5.0.2 on 2024-02-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "App_Payment",
            "0005_alter_patient_cabin_bill_alter_patient_medicine_bill_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentModel",
        ),
        migrations.AlterField(
            model_name="patient",
            name="cabin_bill",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medicine_bill",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="patient",
            name="reports_bill",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="patient",
            name="total_bill",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
