# Generated by Django 3.2.5 on 2024-02-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_BuyMedicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='paymentPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='totalBill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cabinNo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
