# Generated by Django 3.2.5 on 2024-02-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_BuyMedicine', '0002_auto_20240223_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inStock', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='paymentPaid',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='totalBill',
        ),
        migrations.AlterField(
            model_name='patient',
            name='cabinNo',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientId',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
