# Generated by Django 5.0.2 on 2024-02-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=10)),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('blood_test', models.BooleanField(default=False)),
                ('x_ray', models.BooleanField(default=False)),
                ('urine_analysis', models.BooleanField(default=False)),
            ],
        ),
    ]
