# Generated by Django 3.2.5 on 2024-02-16 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_AllocateBed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='bed_number',
            new_name='bedNumber',
        ),
        migrations.RenameField(
            model_name='bed',
            old_name='bed_type',
            new_name='bedType',
        ),
        migrations.RenameField(
            model_name='bed',
            old_name='is_occupied',
            new_name='isOccupied',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='assigned_bed',
            new_name='assignedBed',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
