# Generated by Django 5.0.2 on 2024-02-15 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getAdmitted', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid 11-digit phone number.', regex='^\\d{11}$')]),
        ),
    ]
