# Generated by Django 5.0.1 on 2024-02-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(help_text="Enter patient's name", max_length=100)),
                ('age', models.IntegerField(help_text="Enter patient's age")),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text="Select patient's gender", max_length=10)),
                ('symptoms', models.TextField(help_text="Enter patient's symptoms")),
                ('diagnosis', models.TextField(help_text='Enter diagnosis')),
                ('prescription', models.TextField(help_text='Enter prescription details')),
                ('doctor_name', models.CharField(help_text="Enter doctor's name", max_length=100)),
                ('specialization', models.CharField(help_text="Enter doctor's specialization", max_length=100)),
            ],
        ),
    ]
