# Generated by Django 5.0.1 on 2024-02-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrescribePatient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_name',
            field=models.CharField(max_length=100),
        ),
    ]
